services:
  db:
    image: postgres:alpine
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      
    ports:
      - "5432:5432"
    networks:
      - backend

  app:
    image: buddy-share-back:latest
    container_name: backend
    restart: unless-stopped
    depends_on:
      - db
    command: ["bun", "run", "container"]
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      SALT: ${SALT}
      PEPPER: ${PEPPER}
      FRONT_PORT: ${FRONT_PORT}
      FRONT_HOST: ${FRONT_HOST}
      PORT: ${PORT}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      COOKIE_SECRET: ${COOKIE_SECRET}    
    ports:
      - "5000:5000"
      # - "1935:1935"
      - "8000:8000"
    networks:
      - backend

  nginx:
    image: nginx-rtmp
    container_name: nginx-rtmp
    restart: unless-stopped
    depends_on:
      - app
    environment:
      HOST: app
    ports:
      - "1935:1935"
      - "8080:8080"
      - "80:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge