name: Pull reqests tests

on: pull_request

jobs:
  PR_tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: 12345
          POSTGRES_USER: admin
          POSTGRES_DB: mydb
        ports:
          - 5400:5432
        # Health check to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: install dependecies
        run: bun install

      - name: run database migrations
        run: bun x prisma db push
        env:
          DATABASE_URL: postgres://admin:12345@localhost:5400/mydb?schema=public

      - name: run tests
        run: bun run test